name: indzooom_android_downloader
description: 该插件可在Android和IOS上实现更快，更简化的下载管理，并具有直接通知和查看下载文件的选项。A plugin to enable faster and more streamlined download management on Android and IOS with option to notify and view the downloaded file directly.
version: 1.0.2+4
homepage: https://github.com/giulianojordao/indzooom_android_downloader

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter