name: indzooom_android_downloader
description: A plugin that uses the Android download manager
version: 1.0.2+3
homepage: https://github.com/giulianojordao/indzooom_android_downloader

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter